version: '3'
services:
  # Migrate DB in development
  setup:
    build: .
    image: imjacinta
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    command: "bin/rails db:migrate"
  # Database
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=imjacinta_development
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  # DB Viewer (pgadmin)
  db_pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: "none"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "3080:80"
  # Webapp
  imjacinta:
    # Build ommitted, done by setup
    image: imjacinta
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3333:3000"
    depends_on:
      - db
      - redis
      - setup
  # Redis
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
  # Sidekiq
  sidekiq:
    image: imjacinta
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - setup
      - redis
      - imjacinta
  # Prometheus
  # prometheus:
    # image: prom/prometheus
    # ports:
      # - "9090:9090"
    # volumes:
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # Grafana
  # grafana:
    # image: grafana/grafana
    # ports:
      # - "9999:3000"
    # volumes:
      # - grafana:/var/lib/grafana
    # depends_on:
      # - prometheus

volumes:
  pgdata:
  grafana:
  redis:
