apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.size }}

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: web
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | default "web" }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
      tier: database
  template:
    metadata:
      labels:
        run: db
        tier: database
    spec:
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      containers:
      - name: db
        image: postgres:9.6-alpine
        envFrom:
        - secretRef:
          name: db-secrets
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: web
spec:
  ports:
  - port: 5432
  selector: 
    run: db
    tier: database
  type: ClusterIP