apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
      tier: database
  template:
    metadata:
      labels:
        run: redis
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: web
spec:
  ports:
  - port: 6379
  selector:
    run: redis
    tier: database
  type: ClusterIP