apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: imjacinta
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  template:
    metadata:
      labels:
        run: db
    spec:
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
      containers:
      - name: db
        image: postgres:9.6-alpine
        envFrom:
        - secretRef:
            name: db-secrets  # POSTGRES_USER, POSTGRES_PASSWORD
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data