apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: imjacinta
spec:
  replicas: 1
  selector: 
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:   # TODO: Persistent storage for the redis queue, in case we get preempted with items in the queue
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
