apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "traefikv2.fullname" . }}
  labels:
    app: {{ template "traefikv2.name" . }}
    chart: {{ template "traefikv2.chart" . }}
    release: {{ .Release.Name | quote }}

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi