# https://docs.traefik.io/routing/providers/kubernetes-crd/

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  # Ensure we can roll an update if ports already exist
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.1
          args:
            - --log.level=INFO
            - --api
            - --api.insecure
            - --entrypoints.web.address=:80
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: admin
              containerPort: 8080
              hostPort: 8000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: traefik
# spec:
#   # type: LoadBalancer
#   # externalIPs:
#     # - 10.0.1.234
#   type: NodePort
#   selector:
#     app: traefik
#   ports:
#     - protocol: TCP
#       nodePort: 80
#       port: 80
#       name: web
#       targetPort: 80
#     - protocol: TCP
#       nodePort: 8000
#       port: 8000
#       name: admin
#       targetPort: 8080

# TODO: https://github.com/kubernetes/kubernetes/issues/9995
# Is traefik about to route inter-node? If so, expose to port 80 directly with hostPort
# https://www.doxsey.net/blog/kubernetes--the-surprisingly-affordable-platform-for-personal-projects
