default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 4 } %>

development:
  <<: *default
  database: imjacinta_development

production:
  <<: *default
  database: imjacinta_prod
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
