# Site settings
title: I'm Jac.in/ta
email: jaci.brunning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Website of Jaci Brunning
baseurl: "/ta"
url: "https://imjac.in" # the base hostname & protocol for your site

twitter_username: jacibrunning
linkedin_username: jacibrunning
github_username:  JacisNonsense

#paginate: 9
#paginate_path: "/page/:num/"

paginate_multiple:
  - paginate: 10
    paginate_path: '/frc-log/:num/'
    sub_dir: '/frc-log'
  - paginate: 10
    paginate_path: '/:num/'
    sub_dir: '__ALL__'

permalink: "/post/:year/:month/:day/:title.html"
future: true

safe: false

excerpt_separator: '<!-- excerpt -->'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

destination: ../_build/html/ta/

plugins: ['jekyll-paginate', 'jekyll-paginate-multiple', 'jekyll-feed']

#excerpt_separator: ""

exclude:
  - "*_DEMO"
  - "*_DISABLED"
