apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "imjacinta.fullname" . }}
data:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_HOST: {{ .Release.Name }}-{{ .Values.db.host }}
  RAILS_ENV: {{ .Values.env }}
  RAILS_SERVE_STATIC_FILES: 'true'
  {{ if and (hasKey .Values "insecure") (eq .Values.insecure true) -}}
  NO_SSL: 'true'  # TODO:
  {{ end -}}