apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "imjacinta.fullname" . }}
  labels:
    app: {{ template "imjacinta.name" . }}
    chart: {{ template "imjacinta.chart" . }}
    release: {{ .Release.Name | quote }}
data:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_HOST: {{ .Release.Name }}-{{ .Values.db.host }}
  RAILS_ENV: {{ .Values.env }}
  RAILS_SERVE_STATIC_FILES: 'true'
  MAILER_HOST: smtp.sendgrid.net
  MAILER_USER: apikey
  {{ if and (hasKey .Values "insecure") (eq .Values.insecure true) -}}
  NO_SSL: 'true'  # TODO:
  {{ end -}}