{{- $subdict := dict "name" "curtincourses" "valspec" .Values.curtincourses -}}
{{- $dict := merge $subdict . -}}
{{ template "rails.deployment" $dict }}
---
{{ template "rails.service" $dict }}
---
{{ template "rails.ingress" $dict }}