{{- $subdict := dict "name" "imjacinta" "valspec" .Values.imjacinta -}}
{{- $dict := merge $subdict . -}}

{{ template "rails.secret" $dict }}
---
{{ template "rails.deployment" $dict }}
---
{{ template "rails.sidekiq" $dict }}
---
{{ template "rails.service" $dict }}
---
{{ template "rails.ingress" $dict }}