apiVersion: v2
name: imjacinta
description: A Helm chart for Kubernetes

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

dependencies:
  # - name: mariadb-galera
  #   version: 0.6.9
  #   repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 8.3.0
    repository: "@stable"
  - name: redis
    version: 10.4.1
    repository: "@stable"
  - name: traefik
    version: 9.18.3
    repository: https://helm.traefik.io/traefik