db:
  user: postgres
  host: postgresql
  secret:
    name: postgresql
    key: postgresql-password
    # name: maria
    # key: mariadb-password

env: production
insecure: true

imjacinta:
  ingress:
    rule: HostRegexp(`{host:.*}`)
  image:
    name: jaci/imjacinta
    tag: 74106a3
  resources:
    requests:
      memory: 600Mi
      cpu: 50m
  sidekiq:
    resources:
      requests:
        memory: 350Mi
        cpu: 50m


curtincourses:
  ingress:
    rule: HostRegexp(`curtincourses{host:.*}`)
  image:
    name: jaci/curtin-courses
    tag: 66cc100
  resources:
    requests:
      memory: 600Mi
      cpu: 50m
  sidekiq:
    resources:
      requests:
        memory: 350Mi
        cpu: 50m

postgresql:
  resources:
    requests:
      memory: 200Mi
      cpu: 50m

traefik:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
  nodeSelector:
    preempt: "false"

# mariadb-galera:
#   nameOverride: maria
#   replicaCount: 2
#   db:
#     user: web

# TODO: Alpine
redis:
  usePassword: false
  fullnameOverride: redis
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
  slave:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
