db:
  user: postgres
  host: postgresql
  secret:
    name: postgresql
    key: postgresql-password
    # name: maria
    # key: mariadb-password

env: production
insecure: false

imjacinta:
  ingress:
    rule: Host(`imjac.in`) || Host(`dev.imjac.in`) || Host(`www.imjac.in`)
  image:
    name: gcr.io/imjacinta/jaci/imjacinta
    tag: 75d8579-dirty
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
  sidekiq:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  redis_db: 0


curtincourses:
  ingress:
    rule: Host(`curtincourses.imjac.in`)
  image:
    name: gcr.io/imjacinta/jaci/curtincourses
    tag: 7ab9bc8
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
  sidekiq:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  redis_db: 1

postgresql:
  resources:
    requests:
      memory: 200Mi
      cpu: 50m
  persistence:
    size: 4Gi

traefik:
  api:
    host: traefik.imjac.in
  tls:
    enabled: true
    email: 'jaci.brunning@gmail.com'
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
  nodeSelector:
    preempt: "false"

# mariadb-galera:
#   nameOverride: maria
#   replicaCount: 2
#   db:
#     user: web

# TODO: Alpine
redis:
  usePassword: false
  fullnameOverride: redis
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
  slave:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
