db:
  user: postgres
  host: postgresql
  secret:
    name: postgresql
    key: postgresql-password
    # name: maria
    # key: mariadb-password

env: production
insecure: false

imjacinta:
  ingress:
    rule: Host(`imjac.in`) || Host(`www.imjac.in`)
  image:
    name: gcr.io/imjacinta/jaci/imjacinta
    tag: 75d8579-dirty
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
  sidekiq:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  redis_db: 0


curtincourses:
  ingress:
    rule: Host(`curtincourses.imjac.in`)
  image:
    name: gcr.io/imjacinta/jaci/curtincourses
    tag: b78bb8b
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
  sidekiq:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  redis_db: 1

postgresql:
  resources:
    requests:
      memory: 200Mi
      cpu: 50m
  persistence:
    size: 4Gi

traefik:
  rule: Host(`traefik.imjac.in`)
  # admin:admin is the default. It gets overridden by deploy.sh :)
  htpasswd: admin:$2y$10$VGrS48pf3mmT.C4TcZL8iO7bRSOlciGWoIORSpLyY/nSkvxVc77yS  # admin:admin

  # Traefik chart adds its own dashboard - but it's not where we want it.
  ingressRoute:
    dashboard:
      enabled: false

  persistence:
    enabled: true
  additionalArguments:
    - "--certificatesresolvers.default.acme.storage=/data/acme.json"
    - "--certificatesresolvers.default.acme.email=jaci.brunning@gmail.com"
    - "--certificatesresolvers.default.acme.tlsChallenge=true"
  service:
    type: NodePort

  # api:
  #   host: traefik.imjac.in
  # tls:
  #   enabled: true
  #   email: 'jaci.brunning@gmail.com'
  ports:
    web:
      nodePort: 30080
      redirectTo: websecure    # Enforce HTTPS
    websecure:
      tls:
        enabled: true
      nodePort: 30443
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
  # nodeSelector:     # For GCP, not required on microk8s
  #   preempt: "false"

# mariadb-galera:
#   nameOverride: maria
#   replicaCount: 2
#   db:
#     user: web

# TODO: Alpine
redis:
  usePassword: false
  fullnameOverride: redis
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
  slave:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
