db:
  user: postgres
  host: postgresql
  secret:
    name: postgresql
    key: postgresql-password
    # name: maria
    # key: mariadb-password

env: production
insecure: true

imjacinta:
  ingress:
    rule: HostRegexp(`{host:.*}`)
  image:
    name: jaci/imjacinta
    tag: 74106a3

curtincourses:
  ingress:
    rule: HostRegexp(`curtincourses{host:.*}`)
  image:
    name: jaci/curtin-courses
    tag: 66cc100

traefikv2:

# mariadb-galera:
#   nameOverride: maria
#   replicaCount: 2
#   db:
#     user: web

# TODO: Alpine
redis:
  usePassword: false
  fullnameOverride: redis
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
